spring.application.name=ms-security
spring.mongodb.uri=mongodb+srv://edissonramirez29529:basesnosql2025@cluster0.wvduhj6.mongodb.net/?appName=Cluster0
spring.mongodb.database=db_security
server.port=8081
# JWT Configuration
# secret must be at least 64 bytes for HS512
jwt.secret=antigravity_monorepo_secure_key_2026_smart_buses_project_esrg_secret_64_bytes
jwt.expiration=3600000
github.client.id=Ov23liU89uguaCF3W96w
github.client.secret=4cf5a56493fd5b0105f370b5c7538aba384e20b4